:icons: font

= Exercice XX : Correction

Variables Nb, i en Entier
Variable Flag en Booleen
Tableau T() en Entier
Debut
Ecrire "Entrez le nombre de valeurs :"
Lire Nb
Redim T(Nb-1)
Pour i ← 0 à Nb – 1
 Ecrire "Entrez le nombre n° ", i + 1
 Lire T(i)
i Suivant
Flag ← Vrai
Pour i ← 1 à Nb – 1
 Si T(i) <> T(i – 1) + 1 Alors
 Flag ← Faux
 FinSi
i Suivant
Si Flag Alors
 Ecrire "Les nombres sont consécutifs"
Sinon
 Ecrire "Les nombres ne sont pas consécutifs"
FinSi
Fin
Cette programmation est sans doute la plus spontanée, mais elle présente le défaut
d'examiner la totalité du tableau, même lorsqu'on découvre dès le départ deux éléments
non consécutifs. Aussi, dans le cas d'un grand tableau, est-elle dispendieuse en temps de
traitement. Une autre manière de procéder serait de sortir de la boucle dès que deux
éléments non consécutifs sont détectés.

La deuxième partie de l'algorithme deviendrait donc :
i ← 1
TantQue T(i) = T(i – 1) + 1 et i < Nb – 1
 i ← i + 1
FinTantQue
Si T(i) = T(i – 1) + 1 Alors
 Ecrire "Les nombres sont consécutifs"
Sinon
 Ecrire "Les nombres ne sont pas consécutifs"
FinSi

